services:
  - type: web
    name: rss-social-tool
    env: python
    runtime: python-3.11.8
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
